export const reviews = [
  {
    id: 1,
    name: "Aarav Shah",
    role: "Full Stack Developer",
    rating: 5,
    text: "The XK Trading Floor helped me understand market trends in real-time. The interface and tools are next level!",
    date: "2025-07-20",
    avatar: "/assets/users/aarav.jpg",
  },
  {
    id: 2,
    name: "Riya Patel",
    role: "Trader",
    rating: 4,
    text: "Great platform with a clean UI. Would love to see more community challenges added!",
    date: "2025-08-10",
    avatar: "/assets/users/riya.jpg",
  },
  {
    id: 3,
    name: "Kunal Mehta",
    role: "Finance Student",
    rating: 5,
    text: "As a beginner, I found the tutorials extremely helpful. The XK Academy is a goldmine!",
    date: "2025-06-05",
    avatar: "/assets/users/kunal.jpg",
  },
  {
    id: 4,
    name: "Ananya Sharma",
    role: "Trader, Mumbai",
    rating: 5,
    text: "XK Academy transformed how I approach trading.",
    date: "2025-05-22",
    avatar: "/assets/users/ananya.jpg",
  },
  {
    id: 5,
    name: "Rahul Verma",
    role: "Swing Trader, Delhi",
    rating: 4,
    text: "The events and community are top-tier.",
    date: "2025-04-12",
    avatar: "/assets/users/rahul.jpg",
  },
];
